[package]
name = "ollie/unifytest"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Unify = "sunkenball/unify@1.0.0"
Signal = "sleitnick/signal@2.0.3"
Promise = "evaera/promise@4.0.0"
ProfileStore = "2jammers/profilestore@0.1.0"
